name: sprucekit_mobile
description: "Flutter plugin for SpruceKit Mobile SDK"
version: 0.13.13
homepage: https://github.com/spruceid/sprucekit-mobile

environment:
  sdk: ^3.10.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  pigeon: ^26.1.0

flutter:
  plugin:
    platforms:
      android:
        package: com.spruceid.sprucekit_mobile
        pluginClass: SprucekitMobilePlugin
      ios:
        pluginClass: SprucekitMobilePlugin
