name: mobile-sdk-ios-app push

on:
  push:
    branches: [main]
    paths:
      - "mobile-sdk-ios-app/**"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.MONOREPO_GH_APP_ID }}
          private-key: ${{ secrets.MONOREPO_GH_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: |
            sprucekit-mobile
            mobile-sdk-ios-app
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
      - name: Push subtree
        run: |
          git subtree push --prefix=mobile-sdk-ios-app/ https://github.com/spruceid/mobile-sdk-ios-app.git main
